# Generated by Django 3.2.6 on 2021-09-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.CharField(max_length=30)),
                ('valid_thru', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=10, null=True)),
                ('cvc', models.CharField(max_length=3)),
                ('card_pw', models.CharField(max_length=2)),
                ('uid', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecobag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='Having', max_length=10)),
                ('lastMarket', models.CharField(max_length=20, null=True)),
                ('market', models.CharField(max_length=20, null=True)),
                ('eid', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('eid', models.CharField(max_length=20)),
                ('rentMarket', models.CharField(max_length=20, null=True)),
                ('returnMarket', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=20)),
                ('count', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('stamp', models.IntegerField(default=0)),
                ('isBlocked', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=20)),
                ('coupon', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
        ),
    ]
