# Generated by Django 3.2.6 on 2021-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='marketName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
