# Generated by Django 3.2.6 on 2021-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='lentcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='returncount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
